//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.Fuel.Integration.VesselReportManagementSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelReportLog
    {
        public long Id { get; set; }
        public long RecordId { get; set; }
        public string FailureMessage { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime Date { get; set; }
    }
}
