//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MITD.AutomaticVoucher.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoucherLog
    {
        public long Id { get; set; }
        public string ExceptionMessage { get; set; }
        public string StackTrace { get; set; }
        public string VoucherType { get; set; }
        public string RefrenceNo { get; set; }
    }
}
