namespace MITD.Fuel.Presentation.Logic.SL.Controllers.Inventory
{
    public class InventoryOperationReferenceTypes
    {
        #region Constants

        public const string EOV_EOM_EOY_FUEL_REPORT_CONSUMPTION = "EOV_EOM_EOY_FUEL_REPORT_CONSUMPTION";

        public const string FUEL_REPORT_DETAIL_RECEIVE = "FUEL_REPORT_DETAIL_RECEIVE";

        public const string FUEL_REPORT_DETAIL_TRANSFER = "FUEL_REPORT_DETAIL_TRANSFER";

        public const string FUEL_REPORT_DETAIL_INCREMENTAL_CORRECTION = "FUEL_REPORT_DETAIL_INCREMENTAL_CORRECTION";

        public const string FUEL_REPORT_DETAIL_DECREMENTAL_CORRECTION = "FUEL_REPORT_DETAIL_DECREMENTAL_CORRECTION";

        public const string CHARTER_IN_START_RECEIPT = "CHARTER_IN_START_RECEIPT";
        public const string CHARTER_IN_START_ADJUSTMENT_RECEIPT = "CHARTER IN START ADJUSTMENT RECEIPT";
        public const string CHARTER_IN_START_ADJUSTMENT_ISSUE = "CHARTER IN START ADJUSTMENT ISSUE";


        public const string CHARTER_IN_END_ISSUE = "CHARTER_IN_END_ISSUE";

        public const string CHARTER_IN_END_INCREMENTAL_CORRECTION = "CHARTER_IN_END_INCREMENTAL_CORRECTION";

        public const string CHARTER_IN_END_DECREMENTAL_CORRECTION = "CHARTER_IN_END_DECREMENTAL_CORRECTION";


        public const string CHARTER_OUT_START_ISSUE = "CHARTER_OUT_START_ISSUE";

        public const string CHARTER_OUT_START_INCREMENTAL_CORRECTION = "CHARTER_OUT_START_INCREMENTAL_CORRECTION";

        public const string CHARTER_OUT_START_DECREMENTAL_CORRECTION = "CHARTER_OUT_START_DECREMENTAL_CORRECTION";

        public const string CHARTER_OUT_END_RECEIPT = "CHARTER_OUT_END_RECEIPT";

        public const string SCRAP_ISSUE = "SCRAP_ISSUE";

        public const string INVENTORY_INITIATION = "INVENTORY_INITIATION";

        public const string ISSUE_TOTAL_RECEIVED_TRUST = "ISSUE_TOTAL_RECEIVED_TRUST";

        public const string INVENTORY_ISSUE_ADJUSTMENT = "INVENTORY_ISSUE_ADJUSTMENT";
        public const string INVENTORY_RECEIPT_ADJUSTMENT = "INVENTORY_RECEIPT_ADJUSTMENT";

        #endregion
    }
}
