//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AsgnVoucherAconts = new HashSet<AsgnVoucherAcont>();
            this.EffectiveFactors = new HashSet<EffectiveFactor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Code { get; set; }
    
        public virtual ICollection<AsgnVoucherAcont> AsgnVoucherAconts { get; set; }
        public virtual ICollection<EffectiveFactor> EffectiveFactors { get; set; }
    }
}
