//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityFlow
    {
        public long Id { get; set; }
        public long WorkflowStepId { get; set; }
        public long WorkflowNextStepId { get; set; }
        public int WorkflowAction { get; set; }
        public int ActionTypeId { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual WorkflowStep WorkflowStep { get; set; }
        public virtual WorkflowStep WorkflowStep1 { get; set; }
    }
}
