//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionType
    {
        public ActionType()
        {
            this.ActivityFlows = new HashSet<ActivityFlow>();
            this.Parties_CustomActions = new HashSet<Parties_CustomActions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ActivityFlow> ActivityFlows { get; set; }
        public virtual ICollection<Parties_CustomActions> Parties_CustomActions { get; set; }
    }
}
