//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveFlowConfig
    {
        public ApproveFlowConfig()
        {
            this.ApproveFlowConfig1 = new HashSet<ApproveFlowConfig>();
            this.ApproveFlowConfigValidFuelUsers = new HashSet<ApproveFlowConfigValidFuelUser>();
        }
    
        public long Id { get; set; }
        public long ActorUserId { get; set; }
        public Nullable<long> NextWorkflowStepId { get; set; }
        public int WithWorkflowAction { get; set; }
        public int State { get; set; }
        public int WorkflowEntity { get; set; }
        public int CurrentWorkflowStage { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<ApproveFlowConfig> ApproveFlowConfig1 { get; set; }
        public virtual ApproveFlowConfig ApproveFlowConfig2 { get; set; }
        public virtual ICollection<ApproveFlowConfigValidFuelUser> ApproveFlowConfigValidFuelUsers { get; set; }
    }
}
