//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApproveFlowConfigValidFuelUser
    {
        public long ApproveFlowConfigId { get; set; }
        public long FuelUserId { get; set; }
    
        public virtual ApproveFlowConfig ApproveFlowConfig { get; set; }
    }
}
