//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Charter
    {
        public Charter()
        {
            this.CharterIns = new HashSet<CharterIn>();
            this.CharterItems = new HashSet<CharterItem>();
            this.CharterOuts = new HashSet<CharterOut>();
            this.FuelReports = new HashSet<FuelReport>();
            this.InventoryOperations = new HashSet<InventoryOperation>();
            this.WorkflowLogs = new HashSet<WorkflowLog>();
        }
    
        public long Id { get; set; }
        public int CurrentState { get; set; }
        public System.DateTime ActionDate { get; set; }
        public int CharterType { get; set; }
        public int CharterEndType { get; set; }
        public long ChartererId { get; set; }
        public long OwnerId { get; set; }
        public long VesselInCompanyId { get; set; }
        public long CurrencyId { get; set; }
        public byte[] TimeStamp { get; set; }
    
        public virtual VesselInCompany VesselInCompany { get; set; }
        public virtual ICollection<CharterIn> CharterIns { get; set; }
        public virtual ICollection<CharterItem> CharterItems { get; set; }
        public virtual ICollection<CharterOut> CharterOuts { get; set; }
        public virtual ICollection<FuelReport> FuelReports { get; set; }
        public virtual ICollection<InventoryOperation> InventoryOperations { get; set; }
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
    }
}
