//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyVesselTankView
    {
        public Nullable<long> Id { get; set; }
        public long VesselInInventoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}
