//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyGoodUnitView
    {
        public Nullable<long> Id { get; set; }
        public Nullable<long> CompanyGoodId { get; set; }
        public long SharedGoodId { get; set; }
        public long CompanyId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string To { get; set; }
        public Nullable<decimal> Coefficient { get; set; }
        public Nullable<decimal> Offset { get; set; }
        public Nullable<long> ParentId { get; set; }
    }
}
