//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOVReportsView
    {
        public int DraftID { get; set; }
        public Nullable<int> ShipID { get; set; }
        public Nullable<int> ConsNo { get; set; }
        public string ShipName { get; set; }
        public string VoyageNo { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public int FuelReportType { get; set; }
        public string PortName { get; set; }
        public int PortTime { get; set; }
        public int AtSeaLatitudeDegree { get; set; }
        public int AtSeaLatitudeMinute { get; set; }
        public int AtSeaLongitudeDegree { get; set; }
        public int AtSeaLongitudeMinute { get; set; }
        public int ObsDist { get; set; }
        public int EngDist { get; set; }
        public int SteamTime { get; set; }
        public int AvObsSpeed { get; set; }
        public int AvEngSpeed { get; set; }
        public int RPM { get; set; }
        public int Slip { get; set; }
        public int WindDir { get; set; }
        public int WindForce { get; set; }
        public int SeaDir { get; set; }
        public int SeaForce { get; set; }
        public int ROBHO { get; set; }
        public int ROBDO { get; set; }
        public int ROBMGO { get; set; }
        public int ROBFW { get; set; }
        public int ConsInPortHO { get; set; }
        public int ConsInPortDO { get; set; }
        public int ConsInPortMGO { get; set; }
        public int ConsInPortFW { get; set; }
        public int ConsAtSeaHO { get; set; }
        public int ConsAtSeaDO { get; set; }
        public int ConsAtSeaMGO { get; set; }
        public int ConsAtSeaFW { get; set; }
        public int ReceivedHO { get; set; }
        public int ReceivedDO { get; set; }
        public int ReceivedMGO { get; set; }
        public int ReceivedFW { get; set; }
        public string ETAPort { get; set; }
        public string ETADate { get; set; }
        public System.DateTime DateIn { get; set; }
        public int IsSM { get; set; }
        public int InPortOrAtSea { get; set; }
        public string ImportDate { get; set; }
        public string ShipCode { get; set; }
        public Nullable<long> VoyageId { get; set; }
    }
}
