//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelReportDetail
    {
        public FuelReportDetail()
        {
            this.InventoryOperations = new HashSet<InventoryOperation>();
            this.OrderItemBalances = new HashSet<OrderItemBalance>();
        }
    
        public long Id { get; set; }
        public long FuelReportId { get; set; }
        public long GoodId { get; set; }
        public Nullable<long> TankId { get; set; }
        public decimal Consumption { get; set; }
        public decimal ROB { get; set; }
        public string ROBUOM { get; set; }
        public Nullable<decimal> Receive { get; set; }
        public Nullable<int> ReceiveType { get; set; }
        public Nullable<int> ReceiveReference_ReferenceType { get; set; }
        public Nullable<long> ReceiveReference_ReferenceId { get; set; }
        public string ReceiveReference_Code { get; set; }
        public Nullable<decimal> Transfer { get; set; }
        public Nullable<int> TransferType { get; set; }
        public Nullable<int> TransferReference_ReferenceType { get; set; }
        public Nullable<long> TransferReference_ReferenceId { get; set; }
        public string TransferReference_Code { get; set; }
        public Nullable<decimal> Correction { get; set; }
        public Nullable<decimal> CorrectionPrice { get; set; }
        public Nullable<int> CorrectionType { get; set; }
        public Nullable<int> CorrectionReference_ReferenceType { get; set; }
        public Nullable<long> CorrectionReference_ReferenceId { get; set; }
        public string CorrectionReference_Code { get; set; }
        public Nullable<long> CorrectionPriceCurrencyId { get; set; }
        public string CorrectionPriceCurrencyISOCode { get; set; }
        public long MeasuringUnitId { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<int> CorrectionPricingType { get; set; }
        public bool IsCorrectionPricingTypeRevised { get; set; }
    
        public virtual FuelReport FuelReport { get; set; }
        public virtual ICollection<InventoryOperation> InventoryOperations { get; set; }
        public virtual ICollection<OrderItemBalance> OrderItemBalances { get; set; }
    }
}
