//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelReportCommandLogDetail
    {
        public long Id { get; set; }
        public long FuelReportCommandLogId { get; set; }
        public string FuelType { get; set; }
        public decimal Consumption { get; set; }
        public decimal ROB { get; set; }
        public Nullable<decimal> Transfer { get; set; }
        public Nullable<decimal> Receive { get; set; }
        public Nullable<decimal> Correction { get; set; }
        public string TankCode { get; set; }
        public string MeasuringUnitCode { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual FuelReportCommandLog FuelReportCommandLog { get; set; }
    }
}
