//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class FuelReportCommandLog
    {
        public FuelReportCommandLog()
        {
            this.FuelReportCommandLogDetails = new HashSet<FuelReportCommandLogDetail>();
        }
    
        public long Id { get; set; }
        public string VesselReportReference { get; set; }
        public string VesselCode { get; set; }
        public int FuelReportType { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime EventDate { get; set; }
        public string VoyageNumber { get; set; }
        public bool IsActive { get; set; }
        public int ProcessState { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Remark { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<FuelReportCommandLogDetail> FuelReportCommandLogDetails { get; set; }
    }
}
