//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.Users_Groups = new HashSet<Users_Groups>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ICollection<Users_Groups> Users_Groups { get; set; }
    }
}
