//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAFIZAccountListView
    {
        public int AccountListID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string AccountCode { get; set; }
        public bool Nature { get; set; }
        public short LevelCode { get; set; }
        public string Name { get; set; }
        public string NameL { get; set; }
        public bool Disabled { get; set; }
    }
}
