//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryUser
    {
        public InventoryUser()
        {
            this.InventoryUsers1 = new HashSet<InventoryUser>();
        }
    
        public int Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Email_Address { get; set; }
        public string IPAddress { get; set; }
        public Nullable<bool> Login { get; set; }
        public string SessionId { get; set; }
        public Nullable<int> UserCreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<InventoryUser> InventoryUsers1 { get; set; }
        public virtual InventoryUser InventoryUser1 { get; set; }
    }
}
