//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.Invoice1 = new HashSet<Invoice>();
            this.InvoiceAdditionalPrices = new HashSet<InvoiceAdditionalPrice>();
            this.InvoiceItems = new HashSet<InvoiceItem>();
            this.WorkflowLogs = new HashSet<WorkflowLog>();
            this.Orders = new HashSet<Order>();
        }
    
        public long Id { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public long CurrencyId { get; set; }
        public int State { get; set; }
        public string Description { get; set; }
        public int DivisionMethod { get; set; }
        public string InvoiceNumber { get; set; }
        public int AccountingType { get; set; }
        public Nullable<long> InvoiceRefrenceId { get; set; }
        public int InvoiceType { get; set; }
        public Nullable<long> TransporterId { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public byte[] TimeStamp { get; set; }
        public long OwnerId { get; set; }
        public bool IsCreditor { get; set; }
        public decimal TotalOfDivisionPrice { get; set; }
    
        public virtual ICollection<Invoice> Invoice1 { get; set; }
        public virtual Invoice Invoice2 { get; set; }
        public virtual ICollection<InvoiceAdditionalPrice> InvoiceAdditionalPrices { get; set; }
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
