//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public JournalEntry()
        {
            this.Segments = new HashSet<Segment>();
        }
    
        public long Id { get; set; }
        public long VoucherId { get; set; }
        public string AccountNo { get; set; }
        public long CurrencyId { get; set; }
        public string Description { get; set; }
        public byte[] TimeStamp { get; set; }
        public string VoucherRef { get; set; }
        public decimal ForeignAmount { get; set; }
        public decimal IrrAmount { get; set; }
        public int Typ { get; set; }
        public Nullable<long> InventoryItemId { get; set; }
    
        public virtual ICollection<Segment> Segments { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
