//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long Id { get; set; }
        public byte[] RowVersion { get; set; }
        public string Code { get; set; }
        public int LogLevelId { get; set; }
        public long PartyId { get; set; }
        public string UserName { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Title { get; set; }
        public string Messages { get; set; }
    
        public virtual EventLog EventLog { get; set; }
        public virtual ExceptionLog ExceptionLog { get; set; }
    }
}
