//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffhireDetail
    {
        public long Id { get; set; }
        public decimal Quantity { get; set; }
        public decimal FeeInVoucherCurrency { get; set; }
        public decimal FeeInMainCurrency { get; set; }
        public byte[] TimeStamp { get; set; }
        public long GoodId { get; set; }
        public long OffhireId { get; set; }
        public Nullable<long> TankId { get; set; }
        public long UnitId { get; set; }
    
        public virtual Offhire Offhire { get; set; }
    }
}
