//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationReference
    {
        public long Id { get; set; }
        public long OperationId { get; set; }
        public int OperationType { get; set; }
        public string ReferenceType { get; set; }
        public string ReferenceNumber { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    }
}
