//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderItemBalances = new HashSet<OrderItemBalance>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
        public decimal Quantity { get; set; }
        public long OrderId { get; set; }
        public long GoodId { get; set; }
        public long MeasuringUnitId { get; set; }
        public byte[] TimeStamp { get; set; }
        public decimal InvoicedInMainUnit { get; set; }
        public decimal ReceivedInMainUnit { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderItemBalance> OrderItemBalances { get; set; }
    }
}
