//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemBalance
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public long OrderItemId { get; set; }
        public decimal QuantityAmountInMainUnit { get; set; }
        public string UnitCode { get; set; }
        public long FuelReportDetailId { get; set; }
        public long InvoiceItemId { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<long> InventoryOperationId { get; set; }
        public Nullable<long> PairingInvoiceItemId { get; set; }
    
        public virtual FuelReportDetail FuelReportDetail { get; set; }
        public virtual InventoryOperation InventoryOperation { get; set; }
        public virtual InvoiceItem InvoiceItem { get; set; }
        public virtual InvoiceItem InvoiceItem1 { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
