//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderItems = new HashSet<OrderItem>();
            this.WorkflowLogs = new HashSet<WorkflowLog>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<long> ReceiverId { get; set; }
        public Nullable<long> TransporterId { get; set; }
        public long OwnerId { get; set; }
        public int OrderType { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<long> FromVesselInCompanyId { get; set; }
        public Nullable<long> ToVesselInCompanyId { get; set; }
        public byte[] TimeStamp { get; set; }
        public int State { get; set; }
    
        public virtual VesselInCompany VesselInCompany { get; set; }
        public virtual VesselInCompany VesselInCompany1 { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
