//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Party
    {
        public Party()
        {
            this.Parties_CustomActions = new HashSet<Parties_CustomActions>();
        }
    
        public long Id { get; set; }
        public string PartyName { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Parties_CustomActions> Parties_CustomActions { get; set; }
        public virtual User User { get; set; }
    }
}
