//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parties_CustomActions
    {
        public long Id { get; set; }
        public long PartyId { get; set; }
        public int ActionTypeId { get; set; }
        public bool IsGranted { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual Party Party { get; set; }
    }
}
