//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scrap
    {
        public Scrap()
        {
            this.InventoryOperations = new HashSet<InventoryOperation>();
            this.ScrapDetails = new HashSet<ScrapDetail>();
            this.WorkflowLogs = new HashSet<WorkflowLog>();
        }
    
        public long Id { get; set; }
        public System.DateTime ScrapDate { get; set; }
        public int State { get; set; }
        public byte[] TimeStamp { get; set; }
        public long SecondPartyId { get; set; }
        public long VesselInCompanyId { get; set; }
    
        public virtual ICollection<InventoryOperation> InventoryOperations { get; set; }
        public virtual VesselInCompany VesselInCompany { get; set; }
        public virtual ICollection<ScrapDetail> ScrapDetails { get; set; }
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
    }
}
