//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public byte[] TimeStamp { get; set; }
        public int SegmentTypeId { get; set; }
        public long JournalEntryId { get; set; }
        public Nullable<long> FreeAccountId { get; set; }
        public Nullable<long> EffectiveFactorId { get; set; }
        public string SegmentTypeCode { get; set; }
        public string SegmentTypeName { get; set; }
    
        public virtual EffectiveFactor EffectiveFactor { get; set; }
        public virtual FreeAccount FreeAccount { get; set; }
        public virtual JournalEntry JournalEntry { get; set; }
    }
}
