//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public Transaction()
        {
            this.TransactionItems = new HashSet<TransactionItem>();
            this.Transactions1 = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public byte Action { get; set; }
        public Nullable<decimal> Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> PricingReferenceId { get; set; }
        public long WarehouseId { get; set; }
        public int StoreTypesId { get; set; }
        public int TimeBucketId { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> SenderReciver { get; set; }
        public string HardCopyNo { get; set; }
        public string ReferenceType { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public Nullable<int> UserCreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual StoreType StoreType { get; set; }
        public virtual ICollection<TransactionItem> TransactionItems { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }
        public virtual Transaction Transaction1 { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
