//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.Goods = new HashSet<Good>();
            this.TransactionItemPrices = new HashSet<TransactionItemPrice>();
            this.TransactionItemPrices1 = new HashSet<TransactionItemPrice>();
            this.TransactionItemPrices2 = new HashSet<TransactionItemPrice>();
            this.TransactionItems = new HashSet<TransactionItem>();
            this.UnitConverts = new HashSet<UnitConvert>();
            this.UnitConverts1 = new HashSet<UnitConvert>();
        }
    
        public long Id { get; set; }
        public string Abbreviation { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsCurrency { get; set; }
        public Nullable<bool> IsBaseCurrency { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> UserCreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<Good> Goods { get; set; }
        public virtual ICollection<TransactionItemPrice> TransactionItemPrices { get; set; }
        public virtual ICollection<TransactionItemPrice> TransactionItemPrices1 { get; set; }
        public virtual ICollection<TransactionItemPrice> TransactionItemPrices2 { get; set; }
        public virtual ICollection<TransactionItem> TransactionItems { get; set; }
        public virtual ICollection<UnitConvert> UnitConverts { get; set; }
        public virtual ICollection<UnitConvert> UnitConverts1 { get; set; }
    }
}
