//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitConvert
    {
        public int Id { get; set; }
        public long UnitId { get; set; }
        public long SubUnitId { get; set; }
        public decimal Coefficient { get; set; }
        public Nullable<System.DateTime> EffectiveDateStart { get; set; }
        public Nullable<System.DateTime> EffectiveDateEnd { get; set; }
        public short RowVersion { get; set; }
        public int UserCreatorId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
