//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users1
    {
        public Nullable<int> Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Email_Address { get; set; }
        public Nullable<int> IPAddress { get; set; }
        public Nullable<int> Login { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> UserCreatorId { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
