//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserInCompanies = new HashSet<UserInCompany>();
            this.Users_Groups = new HashSet<Users_Groups>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool Active { get; set; }
        public long CompanyId { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual ICollection<UserInCompany> UserInCompanies { get; set; }
        public virtual ICollection<Users_Groups> Users_Groups { get; set; }
    }
}
