//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voyage
    {
        public long Id { get; set; }
        public string VoyageNumber { get; set; }
        public string Description { get; set; }
        public long VesselInCompanyId { get; set; }
        public long CompanyId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual VesselInCompany VesselInCompany { get; set; }
    }
}
