//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAmendments
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStep
    {
        public WorkflowStep()
        {
            this.ActivityFlows = new HashSet<ActivityFlow>();
            this.ActivityFlows1 = new HashSet<ActivityFlow>();
            this.WorkflowLogs = new HashSet<WorkflowLog>();
        }
    
        public long Id { get; set; }
        public long WorkflowId { get; set; }
        public int State { get; set; }
        public int CurrentWorkflowStage { get; set; }
    
        public virtual ICollection<ActivityFlow> ActivityFlows { get; set; }
        public virtual ICollection<ActivityFlow> ActivityFlows1 { get; set; }
        public virtual Workflow Workflow { get; set; }
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
    }
}
